--  Copyright (C) 2020 Glen Cornell <glen.m.cornell@gmail.com>
--  
--  This program is free software: you can redistribute it and/or
--  modify it under the terms of the GNU General Public License as
--  published by the Free Software Foundation, either version 3 of the
--  License, or (at your option) any later version.
--
--  This program is distributed in the hope that it will be useful,
--  but WITHOUT ANY WARRANTY; without even the implied warranty of
--  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
--  General Public License for more details.
--
--  You should have received a copy of the GNU General Public License
--  along with this program.  If not, see
--  <http://www.gnu.org/licenses/>.

-- Suppress warning generated by referencing internal GNAT packages.
pragma Warnings (Off, """System.Os_Lib"" is an internal GNAT unit");
with System.Os_Lib;
pragma Warnings (Off, """System.Os_Lib"" is an internal GNAT unit");

package body Sockets.Can_Thin is
   
   --------------------------
   -- Socket_Error_Message --
   --------------------------
   
   function Socket_Error_Message
     (Errno : Integer) return String
   is
   begin
      return System.Os_Lib.Errno_Message (Errno, Default => "Unknown system error");
   end Socket_Error_Message;
   
end Sockets.Can_Thin;
