-- Suppress warning generated by referencing internal GNAT packages.
pragma Warnings (Off, """System.Os_Lib"" is an internal GNAT unit");
with System.Os_Lib;
pragma Warnings (Off, """System.Os_Lib"" is an internal GNAT unit");

package body Sockets.Can_Thin is
   
   --------------------------
   -- Socket_Error_Message --
   --------------------------
   
   function Socket_Error_Message
     (Errno : Integer) return String
   is
   begin
      return System.Os_Lib.Errno_Message (Errno, Default => "Unknown system error");
   end Socket_Error_Message;
   
end Sockets.Can_Thin;
